export default {
    action: {
        ADD_SERVICE: 'ADD_SERVICE',
        DELETE_SERVICE: 'DELETE_SERVICE',
        UPDATE_SERVICE: 'UPDATE_SERVICE',

        SET_NAME: 'SET_NAME',
        SET_PRICE: 'SET_PRICE',
        SET_IMAGE: 'SET_IMAGE',
        SET_DESCRIPTION: 'SET_DESCRIPTION',
        SET_DURATION: 'SET_DURATION',
        SET_DURATION_MODE: 'SET_DURATION_MODE',
        SET_PRICE_VARIES: 'SET_PRICE_VARIES',
        RESET_STATE: 'RESET_STATE',
    },
    string: {
        TOTAL_DURATION: 'TOTAL_DURATION',
        START_DURATION: 'START_DURATION',
        PROCESS_DURATION: 'PROCESS_DURATION',
        END_DURATION: 'END_DURATION',
    },
}